Jenkins

diff --git a/service-registry/JenkinsFile b/service-registry/JenkinsFile
--- a/service-registry/JenkinsFile
+++ b/service-registry/JenkinsFile
@@ -19,6 +19,17 @@ pipeline {
             }
         }
 
+//         stage('Static Code Analysis') {
+//             environment {
+//                 SONAR_URL = "http://52.149.213.148:9000"
+//             }
+//             steps {
+//                 withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
+//                     sh 'mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
+//                 }
+//             }
+//         }
+
         stage('Build and Push Docker Image') {
             environment {
                 DOCKER_IMAGE = "algabrizaid/serviceregistry:${imageTag}"
@@ -27,9 +38,7 @@ pipeline {
             }
             steps {
                 script {
-                    dir('service-registry') {
-                        sh 'docker build -t ${DOCKER_IMAGE} .'
-                    }
+                    sh 'docker build -t ${DOCKER_IMAGE} ./service-registry'
                     def dockerImage = docker.image("${DOCKER_IMAGE}")
                     docker.withRegistry('https://index.docker.io/v1/', "dockerhub") {
                         dockerImage.push()
@@ -43,30 +52,32 @@ pipeline {
                 script {
                     echo "Current directory: ${pwd()}"
                     def cloneDir = 'GitOps'
-                    sh "rm -rf ${cloneDir}"
+                     sh "rm -rf ${cloneDir}"
                     if (!fileExists(cloneDir)) {
+
                         sh "git clone https://github.com/zaidgabri/GitOps.git ${cloneDir}"
                     }
 
                     gitConfigure()
 
-                    echo "File content before sed:"
-                    sh "cat ${cloneDir}/k8s/service-registry-deployment.yml"
+                    def manifestsDir = "${cloneDir}/k8s"
+                    def newImageLine = "image: ${registryName}:${imageTag}"
 
-                    dir(cloneDir) {
-                        sh "sed -i 's|image: algabrizaid/serviceregistry:latest.*|image: algabrizaid/serviceregistry:${imageTag}|' k8s/service-registry-deployment.yml || echo 'sed command failed'"
-                    }
+                    echo "File content before sed:"
+                    sh "cat ${manifestsDir}/service-registry-deployment.yml"
+
+                    sh "sed -i 's|image: algabrizaid/serviceregistry:latest.*|${newImageLine}|' ${manifestsDir}/service-registry-deployment.yml || echo 'sed command failed'"
 
                     echo "File content after sed:"
-                    sh "cat ${cloneDir}/k8s/service-registry-deployment.yml"
+                    sh "cat ${manifestsDir}/service-registry-deployment.yml"
 
                     withCredentials([usernamePassword(credentialsId: 'git', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                         dir(cloneDir) {
                             sh "git status"
                             sh "git add ."
-                            sh "git status"
+                            sh "git status" // Print status again to verify changes
                             sh "git commit -m 'Update image tag in Kubernetes manifests'"
-                        
+                            sh "git pull"
                             sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/zaidgabri/GitOps.git HEAD:main"
                         }
                     }
