path

diff --git a/service-registry/JenkinsFile b/service-registry/JenkinsFile
--- a/service-registry/JenkinsFile
+++ b/service-registry/JenkinsFile
@@ -28,7 +28,6 @@ pipeline {
             steps {
                 script {
                     dir('service-registry') {
-                        // Change the context to the service-registry directory
                         sh 'docker build -t ${DOCKER_IMAGE} .'
                     }
                     def dockerImage = docker.image("${DOCKER_IMAGE}")
@@ -51,25 +50,21 @@ pipeline {
 
                     gitConfigure()
 
-                    def manifestsDir = "${cloneDir}/k8s"
-                    def newImageLine = "image: ${registryName}:${imageTag}"
-
                     echo "File content before sed:"
-                    sh "cat ${manifestsDir}/service-registry-deployment.yml"
+                    sh "cat ${cloneDir}/k8s/service-registry-deployment.yml"
 
-                    // Run sed in the GitOps directory
                     dir(cloneDir) {
-                        sh "sed -i 's|image: algabrizaid/serviceregistry:latest.*|${newImageLine}|' ${manifestsDir}/service-registry-deployment.yml || echo 'sed command failed'"
+                        sh "sed -i 's|image: algabrizaid/serviceregistry:latest.*|image: algabrizaid/serviceregistry:${imageTag}|' k8s/service-registry-deployment.yml || echo 'sed command failed'"
                     }
 
                     echo "File content after sed:"
-                    sh "cat ${manifestsDir}/service-registry-deployment.yml"
+                    sh "cat ${cloneDir}/k8s/service-registry-deployment.yml"
 
                     withCredentials([usernamePassword(credentialsId: 'git', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                         dir(cloneDir) {
                             sh "git status"
                             sh "git add ."
-                            sh "git status" // Print status again to verify changes
+                            sh "git status"
                             sh "git commit -m 'Update image tag in Kubernetes manifests'"
                             sh "git pull"
                             sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/zaidgabri/GitOps.git HEAD:main"
