adding Jenkins and Dockerfile"

diff --git a/service-registry/JenkinsFile b/service-registry/JenkinsFile
--- a/service-registry/JenkinsFile
+++ b/service-registry/JenkinsFile
@@ -19,17 +19,6 @@ pipeline {
             }
         }
 
-//         stage('Static Code Analysis') {
-//             environment {
-//                 SONAR_URL = "http://52.149.213.148:9000"
-//             }
-//             steps {
-//                 withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
-//                     sh 'mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
-//                 }
-//             }
-//         }
-
         stage('Build and Push Docker Image') {
             environment {
                 DOCKER_IMAGE = "algabrizaid/serviceregistry:${imageTag}"
@@ -38,7 +27,10 @@ pipeline {
             }
             steps {
                 script {
-                    sh 'docker build -t ${DOCKER_IMAGE} ./service-registry'
+                    dir('service-registry') {
+                        // Change the context to the service-registry directory
+                        sh 'docker build -t ${DOCKER_IMAGE} .'
+                    }
                     def dockerImage = docker.image("${DOCKER_IMAGE}")
                     docker.withRegistry('https://index.docker.io/v1/', "dockerhub") {
                         dockerImage.push()
@@ -52,9 +44,8 @@ pipeline {
                 script {
                     echo "Current directory: ${pwd()}"
                     def cloneDir = 'GitOps'
-                     sh "rm -rf ${cloneDir}"
+                    sh "rm -rf ${cloneDir}"
                     if (!fileExists(cloneDir)) {
-
                         sh "git clone https://github.com/zaidgabri/GitOps.git ${cloneDir}"
                     }
 
@@ -66,7 +57,10 @@ pipeline {
                     echo "File content before sed:"
                     sh "cat ${manifestsDir}/service-registry-deployment.yml"
 
-                    sh "sed -i 's|image: algabrizaid/serviceregistry:latest.*|${newImageLine}|' ${manifestsDir}/service-registry-deployment.yml || echo 'sed command failed'"
+                    // Run sed in the GitOps directory
+                    dir(cloneDir) {
+                        sh "sed -i 's|image: algabrizaid/serviceregistry:latest.*|${newImageLine}|' ${manifestsDir}/service-registry-deployment.yml || echo 'sed command failed'"
+                    }
 
                     echo "File content after sed:"
                     sh "cat ${manifestsDir}/service-registry-deployment.yml"
