path

diff --git a/service-registry/JenkinsFile b/service-registry/JenkinsFile
--- a/service-registry/JenkinsFile
+++ b/service-registry/JenkinsFile
@@ -27,7 +27,9 @@ pipeline {
             }
             steps {
                 script {
-                    sh 'docker build -t ${DOCKER_IMAGE} ./service-registry'
+                    dir('service-registry') {
+                        sh 'docker build -t ${DOCKER_IMAGE} .'
+                    }
                     def dockerImage = docker.image("${DOCKER_IMAGE}")
                     docker.withRegistry('https://index.docker.io/v1/', "dockerhub") {
                         dockerImage.push()
@@ -48,24 +50,23 @@ pipeline {
 
                     gitConfigure()
 
-                    def manifestsDir = "${cloneDir}/k8s"
-                    def newImageLine = "image: ${registryName}:${imageTag}"
-
                     echo "File content before sed:"
-                    sh "cat ${manifestsDir}/service-registry-deployment.yml"
+                    sh "cat ${cloneDir}/k8s/service-registry-deployment.yml"
 
-                    sh "awk -v tag=${imageTag} 'BEGIN{OFS=FS=\":\"} /image: algabrizaid\\/serviceregistry:latest/{\$2=tag} 1' ${manifestsDir}/service-registry-deployment.yml > ${manifestsDir}/tmpfile && mv ${manifestsDir}/tmpfile ${manifestsDir}/service-registry-deployment.yml"
+                    dir(cloneDir) {
+                        sh "sed -i 's|image: algabrizaid/serviceregistry:latest.*|image: algabrizaid/serviceregistry:${imageTag}|' k8s/service-registry-deployment.yml || echo 'sed command failed'"
+                    }
 
-                    echo "File content after updating image tag:"
-                    sh "cat ${manifestsDir}/service-registry-deployment.yml"
+                    echo "File content after sed:"
+                    sh "cat ${cloneDir}/k8s/service-registry-deployment.yml"
 
                     withCredentials([usernamePassword(credentialsId: 'git', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                         dir(cloneDir) {
                             sh "git status"
                             sh "git add ."
-                            sh "git status" // Print status again to verify changes
+                            sh "git status"
                             sh "git commit -m 'Update image tag in Kubernetes manifests'"
-                            sh "git pull"
+                        
                             sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/zaidgabri/GitOps.git HEAD:main"
                         }
                     }
